import {
  Loader2,
  CheckCircle2,
  AlertCircle,
  XCircle,
  Info,
  CircleHelp,
  Terminal,
  Mail,
  User,
  Settings,
  Bell,
  Shield,
  Palette,
  Globe,
  DollarSign,
  Map,
  LogOut,
  ArrowLeft,
  ArrowRight,
  Check,
  X,
  Plus,
  Minus,
  Pencil,
  Trash,
  Save,
  Upload,
  Download,
  Lock,
  Unlock,
  Calendar,
  AlertTriangle,
  Bookmark,
  ExternalLink,
  Eye,
  EyeOff,
} from 'lucide-react'

export const Icons = {
  spinner: Loader2,
  success: CheckCircle2,
  error: XCircle,
  warning: AlertCircle,
  info: Info,
  help: CircleHelp,
  terminal: Terminal,
  email: Mail,
  user: User,
  settings: Settings,
  bell: Bell,
  shield: Shield,
  palette: Palette,
  globe: Globe,
  dollar: DollarSign,
  map: Map,
  logout: LogOut,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  check: Check,
  x: X,
  plus: Plus,
  minus: Minus,
  edit: Pencil,
  delete: Trash,
  save: Save,
  upload: Upload,
  download: Download,
  lock: Lock,
  unlock: Unlock,
  calendar: Calendar,
  alert: AlertTriangle,
  bookmark: Bookmark,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
}
