name: Backend Build and Test

on:
  push:
    branches:
      - master  # Update if you're using a different branch
  pull_request:
    branches:
      - master

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '23'  # Updated to JDK 23

      - name: Set up PostgreSQL Driver
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Test Backend
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.DATABASE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          SECURITY_USER_NAME: ${{ secrets.SECURITY_USER_NAME }}
          SECURITY_USER_PASSWORD: ${{ secrets.SECURITY_USER_PASSWORD }}
        run: ./gradlew clean build

      - name: Run Tests
        run: ./gradlew test
